### ISSUE TITLE
How does termux install Python ta-lib?

### ISSUE THREAD

**Issue by ymstd** [myfreess/Mytermuxdoc#4]
Because the directories of termux and Linux are different, they don't know how to compile. Can someone who understands write an installation method?

**Comment by myfreess** [comment]
请问你是一位中文用户吗？ @ymstd 
如果只是因为 目录的问题，请尝试：
```bash
pkg in proot -y
termux-chroot
```

**Comment by ymstd** [comment]
这里是ta-lib安装方法https://www.jianshu.com/p/a4204ce921ef
$ wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz #下载
$ tar -xvf ta-lib-0.4.0-src.tar.gz  # 解压
$ cd ta-lib # 进入目录
$ ./configure --prefix=/usr
$ make
$ make install
我解压了进入目录
$ ./configure --prefix=/data/data/com.termux/files/usr或./configure --prefix=/usr都
$ -bash: ./configure: /bin/sh: bad interpreter: No such file or directory
是不是configure里面的路径和termux不一样，想问问怎么解决？ @myfreess

**Comment by myfreess** [comment]
configure默认的shebang不适合Termux,修复它：
```bash
find . -name 'config.sub' -exec chmod u+w '{}' \; -exec cp -f "${PREFIX}/share/libtool/build-aux/config.sub" '{}' \; find . -name 'config.guess' -exec chmod u+w '{}' \; -exec cp -f "${PREFIX}/share/libtool/build-aux/config.guess" '{}' \;
termux-fix-shebang configure
```
但是想编译成功，最好先检查一下
```bash
pkg in silversearcher-ag -y
ag -i /tmp .
ag -i /usr .
ag -i /etc .
```
很多只适合Unix的东西都有硬编码的坏习惯，如果发现有，另行处理(我不想在issues里谈，回头写一篇文档。

最后，劝一句，我见过有开发者在Termux上编译自己项目都失败的例子(repo在此为证：https://github.com/liyanrui/orez    

编译很难的，不如找个别的东西代替吧。看看Termux主开发者fornwall,他给几百个软件包都写了补丁。可能你为了编译这个还要把C给学会，还搭上m4和Makefile。

**Comment by ymstd** [comment]
好的，多谢你热心解答。 @myfreess

**Comment by myfreess** [comment]
也许可以用atilo曲线救国 @ymstd

**Comment by genspider** [comment]
uwsgi模块安装不了，提示sys/sem.h文件找不到。能帮忙解决下吗

**Comment by myfreess** [comment]
@genspider 请去了解一下C的头文件，另外不要跨issues
